// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	entity "milestone2/internal/entity"

	mock "github.com/stretchr/testify/mock"
)

// CarsService is an autogenerated mock type for the CarsService type
type CarsService struct {
	mock.Mock
}

// Create provides a mock function with given fields: req
func (_m *CarsService) Create(req entity.CreateRentalCarsRequest) (entity.CarsResponse, error) {
	ret := _m.Called(req)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 entity.CarsResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(entity.CreateRentalCarsRequest) (entity.CarsResponse, error)); ok {
		return rf(req)
	}
	if rf, ok := ret.Get(0).(func(entity.CreateRentalCarsRequest) entity.CarsResponse); ok {
		r0 = rf(req)
	} else {
		r0 = ret.Get(0).(entity.CarsResponse)
	}

	if rf, ok := ret.Get(1).(func(entity.CreateRentalCarsRequest) error); ok {
		r1 = rf(req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAll provides a mock function with no fields
func (_m *CarsService) GetAll() ([]entity.CarsResponse, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []entity.CarsResponse
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]entity.CarsResponse, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []entity.CarsResponse); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.CarsResponse)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetById provides a mock function with given fields: id
func (_m *CarsService) GetById(id int) (entity.CarsResponse, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetById")
	}

	var r0 entity.CarsResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (entity.CarsResponse, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(int) entity.CarsResponse); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(entity.CarsResponse)
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewCarsService creates a new instance of CarsService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCarsService(t interface {
	mock.TestingT
	Cleanup(func())
}) *CarsService {
	mock := &CarsService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
