// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	entity "milestone2/internal/entity"

	mock "github.com/stretchr/testify/mock"
)

// CarsRepository is an autogenerated mock type for the CarsRepository type
type CarsRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: car
func (_m *CarsRepository) Create(car *entity.Cars) error {
	ret := _m.Called(car)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*entity.Cars) error); ok {
		r0 = rf(car)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAll provides a mock function with no fields
func (_m *CarsRepository) GetAll() ([]entity.Cars, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []entity.Cars
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]entity.Cars, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []entity.Cars); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Cars)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetById provides a mock function with given fields: id
func (_m *CarsRepository) GetById(id int) (entity.Cars, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetById")
	}

	var r0 entity.Cars
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (entity.Cars, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(int) entity.Cars); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(entity.Cars)
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewCarsRepository creates a new instance of CarsRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCarsRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *CarsRepository {
	mock := &CarsRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
