// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	entity "milestone2/internal/entity"

	mock "github.com/stretchr/testify/mock"
)

// PaymentService is an autogenerated mock type for the PaymentService type
type PaymentService struct {
	mock.Mock
}

// CreatePayment provides a mock function with given fields: userId, req
func (_m *PaymentService) CreatePayment(userId int, req entity.CreatePaymentRequest) (entity.PaymentInfoResponse, error) {
	ret := _m.Called(userId, req)

	if len(ret) == 0 {
		panic("no return value specified for CreatePayment")
	}

	var r0 entity.PaymentInfoResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(int, entity.CreatePaymentRequest) (entity.PaymentInfoResponse, error)); ok {
		return rf(userId, req)
	}
	if rf, ok := ret.Get(0).(func(int, entity.CreatePaymentRequest) entity.PaymentInfoResponse); ok {
		r0 = rf(userId, req)
	} else {
		r0 = ret.Get(0).(entity.PaymentInfoResponse)
	}

	if rf, ok := ret.Get(1).(func(int, entity.CreatePaymentRequest) error); ok {
		r1 = rf(userId, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAllPayment provides a mock function with no fields
func (_m *PaymentService) GetAllPayment() ([]entity.PaymentInfoResponse, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAllPayment")
	}

	var r0 []entity.PaymentInfoResponse
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]entity.PaymentInfoResponse, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []entity.PaymentInfoResponse); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.PaymentInfoResponse)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByIdPayment provides a mock function with given fields: id
func (_m *PaymentService) GetByIdPayment(id int) (entity.PaymentInfoResponse, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetByIdPayment")
	}

	var r0 entity.PaymentInfoResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (entity.PaymentInfoResponse, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(int) entity.PaymentInfoResponse); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(entity.PaymentInfoResponse)
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByUserIdPayment provides a mock function with given fields: userId
func (_m *PaymentService) GetByUserIdPayment(userId int) ([]entity.PaymentInfoResponse, error) {
	ret := _m.Called(userId)

	if len(ret) == 0 {
		panic("no return value specified for GetByUserIdPayment")
	}

	var r0 []entity.PaymentInfoResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(int) ([]entity.PaymentInfoResponse, error)); ok {
		return rf(userId)
	}
	if rf, ok := ret.Get(0).(func(int) []entity.PaymentInfoResponse); ok {
		r0 = rf(userId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.PaymentInfoResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(userId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TransactionUpdatePayment provides a mock function with given fields: paymentId
func (_m *PaymentService) TransactionUpdatePayment(paymentId int) (entity.PaidPaymentResponse, error) {
	ret := _m.Called(paymentId)

	if len(ret) == 0 {
		panic("no return value specified for TransactionUpdatePayment")
	}

	var r0 entity.PaidPaymentResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (entity.PaidPaymentResponse, error)); ok {
		return rf(paymentId)
	}
	if rf, ok := ret.Get(0).(func(int) entity.PaidPaymentResponse); ok {
		r0 = rf(paymentId)
	} else {
		r0 = ret.Get(0).(entity.PaidPaymentResponse)
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(paymentId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewPaymentService creates a new instance of PaymentService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPaymentService(t interface {
	mock.TestingT
	Cleanup(func())
}) *PaymentService {
	mock := &PaymentService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
