// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	entity "milestone2/internal/entity"

	mock "github.com/stretchr/testify/mock"
)

// PaymentRepository is an autogenerated mock type for the PaymentRepository type
type PaymentRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: payment
func (_m *PaymentRepository) Create(payment *entity.Payments) error {
	ret := _m.Called(payment)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*entity.Payments) error); ok {
		r0 = rf(payment)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAll provides a mock function with no fields
func (_m *PaymentRepository) GetAll() ([]entity.Payments, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []entity.Payments
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]entity.Payments, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []entity.Payments); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Payments)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetById provides a mock function with given fields: id
func (_m *PaymentRepository) GetById(id int) (entity.Payments, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetById")
	}

	var r0 entity.Payments
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (entity.Payments, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(int) entity.Payments); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(entity.Payments)
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByUserId provides a mock function with given fields: userId
func (_m *PaymentRepository) GetByUserId(userId int) ([]entity.Payments, error) {
	ret := _m.Called(userId)

	if len(ret) == 0 {
		panic("no return value specified for GetByUserId")
	}

	var r0 []entity.Payments
	var r1 error
	if rf, ok := ret.Get(0).(func(int) ([]entity.Payments, error)); ok {
		return rf(userId)
	}
	if rf, ok := ret.Get(0).(func(int) []entity.Payments); ok {
		r0 = rf(userId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Payments)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(userId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TransactionUpdate provides a mock function with given fields: paymentId, totalDay, availabilityUntil
func (_m *PaymentRepository) TransactionUpdate(paymentId int, totalDay int, availabilityUntil string) error {
	ret := _m.Called(paymentId, totalDay, availabilityUntil)

	if len(ret) == 0 {
		panic("no return value specified for TransactionUpdate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int, int, string) error); ok {
		r0 = rf(paymentId, totalDay, availabilityUntil)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewPaymentRepository creates a new instance of PaymentRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPaymentRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *PaymentRepository {
	mock := &PaymentRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
