// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	entity "milestone2/internal/entity"

	mock "github.com/stretchr/testify/mock"
)

// RentalLogsService is an autogenerated mock type for the RentalLogsService type
type RentalLogsService struct {
	mock.Mock
}

// GetByCarId
func (_m *RentalLogsService) GetByCarId(carId int) (logs []entity.RentalLogs, err error) {
	return nil, nil
}

// GetAllLogs provides a mock function with no fields
func (_m *RentalLogsService) GetAllLogs() ([]entity.RentalLogsResponseAdmin, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAllLogs")
	}

	var r0 []entity.RentalLogsResponseAdmin
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]entity.RentalLogsResponseAdmin, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []entity.RentalLogsResponseAdmin); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.RentalLogsResponseAdmin)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByIdLogs provides a mock function with given fields: id
func (_m *RentalLogsService) GetByIdLogs(id int) (entity.RentalLogsResponseAdmin, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetByIdLogs")
	}

	var r0 entity.RentalLogsResponseAdmin
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (entity.RentalLogsResponseAdmin, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(int) entity.RentalLogsResponseAdmin); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(entity.RentalLogsResponseAdmin)
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByUserIdLogs provides a mock function with given fields: userId
func (_m *RentalLogsService) GetByUserIdLogs(userId int) ([]entity.RentalLogsResponseUser, error) {
	ret := _m.Called(userId)

	if len(ret) == 0 {
		panic("no return value specified for GetByUserIdLogs")
	}

	var r0 []entity.RentalLogsResponseUser
	var r1 error
	if rf, ok := ret.Get(0).(func(int) ([]entity.RentalLogsResponseUser, error)); ok {
		return rf(userId)
	}
	if rf, ok := ret.Get(0).(func(int) []entity.RentalLogsResponseUser); ok {
		r0 = rf(userId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.RentalLogsResponseUser)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(userId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewRentalLogsService creates a new instance of RentalLogsService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRentalLogsService(t interface {
	mock.TestingT
	Cleanup(func())
}) *RentalLogsService {
	mock := &RentalLogsService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
