// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	entity "milestone2/internal/entity"

	mock "github.com/stretchr/testify/mock"
)

// RentalLogsRepository is an autogenerated mock type for the RentalLogsRepository type
type RentalLogsRepository struct {
	mock.Mock
}

// GetAll provides a mock function with no fields
func (_m *RentalLogsRepository) GetAll() ([]entity.RentalLogs, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []entity.RentalLogs
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]entity.RentalLogs, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []entity.RentalLogs); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.RentalLogs)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetById provides a mock function with given fields: id
func (_m *RentalLogsRepository) GetById(id int) (entity.RentalLogs, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetById")
	}

	var r0 entity.RentalLogs
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (entity.RentalLogs, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(int) entity.RentalLogs); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(entity.RentalLogs)
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByUserId provides a mock function with given fields: userId
func (_m *RentalLogsRepository) GetByUserId(userId int) ([]entity.RentalLogs, error) {
	ret := _m.Called(userId)

	if len(ret) == 0 {
		panic("no return value specified for GetByUserId")
	}

	var r0 []entity.RentalLogs
	var r1 error
	if rf, ok := ret.Get(0).(func(int) ([]entity.RentalLogs, error)); ok {
		return rf(userId)
	}
	if rf, ok := ret.Get(0).(func(int) []entity.RentalLogs); ok {
		r0 = rf(userId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.RentalLogs)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(userId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewRentalLogsRepository creates a new instance of RentalLogsRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRentalLogsRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *RentalLogsRepository {
	mock := &RentalLogsRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
