// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	entity "milestone2/internal/entity"

	mock "github.com/stretchr/testify/mock"
)

// UserService is an autogenerated mock type for the UserService type
type UserService struct {
	mock.Mock
}

// CreateUser provides a mock function with given fields: user
func (_m *UserService) CreateUser(user entity.User) (entity.UserResponse, error) {
	ret := _m.Called(user)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 entity.UserResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(entity.User) (entity.UserResponse, error)); ok {
		return rf(user)
	}
	if rf, ok := ret.Get(0).(func(entity.User) entity.UserResponse); ok {
		r0 = rf(user)
	} else {
		r0 = ret.Get(0).(entity.UserResponse)
	}

	if rf, ok := ret.Get(1).(func(entity.User) error); ok {
		r1 = rf(user)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserByEmail provides a mock function with given fields: email, password
func (_m *UserService) GetUserByEmail(email string, password string) (string, error) {
	ret := _m.Called(email, password)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByEmail")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (string, error)); ok {
		return rf(email, password)
	}
	if rf, ok := ret.Get(0).(func(string, string) string); ok {
		r0 = rf(email, password)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(email, password)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserById provides a mock function with given fields: id
func (_m *UserService) GetUserById(id int) (entity.UserResponse, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetUserById")
	}

	var r0 entity.UserResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (entity.UserResponse, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(int) entity.UserResponse); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(entity.UserResponse)
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserValidation provides a mock function with given fields: code, email
func (_m *UserService) GetUserValidation(code string, email string) (entity.UserResponse, error) {
	ret := _m.Called(code, email)

	if len(ret) == 0 {
		panic("no return value specified for GetUserValidation")
	}

	var r0 entity.UserResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (entity.UserResponse, error)); ok {
		return rf(code, email)
	}
	if rf, ok := ret.Get(0).(func(string, string) entity.UserResponse); ok {
		r0 = rf(code, email)
	} else {
		r0 = ret.Get(0).(entity.UserResponse)
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(code, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewUserService creates a new instance of UserService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserService(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserService {
	mock := &UserService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
